### ISSUE TITLE
Placeholder %quests_player_compass_quest_name%

### ISSUE THREAD

**Issue by Blskk** [PikaMug/PlaceholderExpansion-Quests#18]
%quests_player_compass_quest_name%

After the task is completed, it will not return the empty value. Instead

**Comment by PikaMug** [comment]
Unable to replicate. Please share more information such as Quests version and an example quest.

**Comment by Blskk** [comment]
```
  '000001':
    name: 击杀10只僵尸
    ask-message: ''
    finish-message: ''
    stages:
      ordered:
        '1':
          mobs-to-kill:
          - Zombie
          mob-amounts:
          - 10
    planner:
      override: false
    options:
      allow-commands: true
      allow-quitting: true
      ignore-silk-touch: true
      use-parties-plugin: true
      share-progress-level: 1
      same-quest-only: true
      share-distance: 0.0
      handle-offline-players: false
      ignore-block-replace: true
```

paper1.20.1  quests version: 5.0.0-rc.3-b440
